#!/usr/bin/env groovy
pipeline {
    agent none
    stages {
        stage('Build'){
            agent{
                any { image 'node:12.16.2' args '-p 3000:3000' }
            }
            steps {
                sh "mvn package -Dmaven.test.skip=true" 
            }
        }
    }
}